language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

jobs:
  allow_failures:
    # now the cattr not support python 3.8
    - python: 3.8

install:
  - pip install pipenv
  - pipenv install --dev
script:
  - make lint
  - make test
  - make coverage

# ignore tags build
branches:
  except:
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/

after_success:
  - codecov