name: pushCheck

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make env
      - name: Check lint with flake8
        run: |
          pipenv run flake8 --ignore E111,E124,E126,E221,E501,w504 --exclude .git,__pycache__
      - name: Test with pytest
        run: |
          pipenv run pytest -s
