name: prCheck

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.7', '3.6', '3.7', '3.8']
      name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make env
      - name: Check lint with flake8
        run: |
          pipenv run flake8 --ignore E111,E124,E126,E221,E501,w504 --exclude .git,__pycache__
      - name: Test with pytest
        run: |
          pipenv run pytest -s
      - uses: codecov/codecov-action@v1
      - name: Codecov
        run: |
          codecov

